# Netlify global settings applied to the whole site.  
# 
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  command = "npm run build"
  publish = "dist/"
  functions = "build/lambda"
  [build.environment]
    NETLIFY = "true"
    NODE_ENV = "production"
    NODE_OPTIONS = "--max_old_space_size=4096"

[context.production]
  [context.production.environment]
    DEPLOY_ENV = "production"
    SITE_ROOT = "https://faa.st"

[context.staging]
  [context.staging.environment]
    DEPLOY_ENV = "staging"
    SITE_ROOT = "https://staging.faast.us"

[context.develop]
  [context.develop.environment]
    DEPLOY_ENV = "develop"

### Main single page app

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

### Path aliases for convencience

[[redirects]]
  from = "/portfolio/*"
  to = "/app/:splat"
  status = 301

[[redirects]]
  from = "/swap/*"
  to = "/app/swap/:splat"
  status = 301

[[redirects]]
  from = "/affiliates/*"
  to = "/app/affiliates/:splat"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "https://medium.com/faast/:splat"
  status = 301
